spring:
  application:
    name: nacos-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.100:8848

    # 使用 Sentinel 作为熔断器
    sentinel:
      transport:
        dashboard: 192.168.99.100:8858

server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: "*"


feign:
  sentinel:
    enabled: true