spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"