spring:
  application:
    name: user-service-provider
dubbo:
  registry:
    address: zookeeper://zookeeper:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: com.f139.provider.service
  application:
    name: ${spring.application.name}