spring:
  application:
    name: nacos-sentinel-spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    sentinel:
      transport:
        dashboard: sentinel:8858
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true



server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'